services:
  error404-ds-bot:
    build: .
    container_name: error404-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
